#ifndef DEVICE_H
# define DEVICE_H

# include <ps2/ps2.h>

# define KEYS_COUNT			0xbe
# define EXTRA_KEYS_CODE	0xe0

# define SCAN1_PRESS_ESC			0x1
# define SCAN1_PRESS_1				0x2
# define SCAN1_PRESS_2				0x3
# define SCAN1_PRESS_3				0x4
# define SCAN1_PRESS_4				0x5
# define SCAN1_PRESS_5				0x6
# define SCAN1_PRESS_6				0x7
# define SCAN1_PRESS_7				0x8
# define SCAN1_PRESS_8				0x9
# define SCAN1_PRESS_9				0xa
# define SCAN1_PRESS_0				0xb
# define SCAN1_PRESS_MINUS			0xc
# define SCAN1_PRESS_EQUAL			0xd
# define SCAN1_PRESS_BACKSPACE		0xe
# define SCAN1_PRESS_TAB			0xf
# define SCAN1_PRESS_Q				0x10
# define SCAN1_PRESS_W				0x11
# define SCAN1_PRESS_E				0x12
# define SCAN1_PRESS_R				0x13
# define SCAN1_PRESS_T				0x14
# define SCAN1_PRESS_Y				0x15
# define SCAN1_PRESS_U				0x16
# define SCAN1_PRESS_I				0x17
# define SCAN1_PRESS_O				0x18
# define SCAN1_PRESS_P				0x19
# define SCAN1_PRESS_LEFT_BRACKET	0x1a
# define SCAN1_PRESS_RIGHT_BRACKET	0x1b
# define SCAN1_PRESS_ENTER			0x1c
# define SCAN1_PRESS_LEFT_CTRL		0x1d
# define SCAN1_PRESS_A				0x1e
# define SCAN1_PRESS_S				0x1f
# define SCAN1_PRESS_D				0x20
# define SCAN1_PRESS_F				0x21
# define SCAN1_PRESS_G				0x22
# define SCAN1_PRESS_H				0x23
# define SCAN1_PRESS_J				0x24
# define SCAN1_PRESS_K				0x25
# define SCAN1_PRESS_L				0x26
# define SCAN1_PRESS_SEMICOLON		0x27
# define SCAN1_PRESS_SINGLE_QUOTE	0x28
# define SCAN1_PRESS_BACKTICK		0x29
# define SCAN1_PRESS_LEFT_SHIFT		0x2a
# define SCAN1_PRESS_BACKSLASH		0x2b
# define SCAN1_PRESS_Z				0x2c
# define SCAN1_PRESS_X				0x2d
# define SCAN1_PRESS_C				0x2e
# define SCAN1_PRESS_V				0x2f
# define SCAN1_PRESS_B				0x30
# define SCAN1_PRESS_N				0x31
# define SCAN1_PRESS_M				0x32
# define SCAN1_PRESS_COMMA			0x33
# define SCAN1_PRESS_DOT			0x34
# define SCAN1_PRESS_SLASH			0x35
# define SCAN1_PRESS_RIGHT_SHIFT	0x36
# define SCAN1_PRESS_KEYPAD_STAR	0x37
# define SCAN1_PRESS_LEFT_ALT		0x38
# define SCAN1_PRESS_SPACE			0x39
# define SCAN1_PRESS_CAPSLOCK		0x3a
# define SCAN1_PRESS_F1				0x3b
# define SCAN1_PRESS_F2				0x3c
# define SCAN1_PRESS_F3				0x3d
# define SCAN1_PRESS_F4				0x3e
# define SCAN1_PRESS_F5				0x3f
# define SCAN1_PRESS_F6				0x40
# define SCAN1_PRESS_F7				0x41
# define SCAN1_PRESS_F8				0x42
# define SCAN1_PRESS_F9				0x43
# define SCAN1_PRESS_F10			0x44
# define SCAN1_PRESS_NUMBERLOCK		0x45
# define SCAN1_PRESS_SCROLLLOCK		0x46
# define SCAN1_PRESS_KEYPAD_7		0x47
# define SCAN1_PRESS_KEYPAD_8		0x48
# define SCAN1_PRESS_KEYPAD_9		0x49
# define SCAN1_PRESS_KEYPAD_MINUS	0x4a
# define SCAN1_PRESS_KEYPAD_4		0x4b
# define SCAN1_PRESS_KEYPAD_5		0x4c
# define SCAN1_PRESS_KEYPAD_6		0x4d
# define SCAN1_PRESS_KEYPAD_PLUS	0x4e
# define SCAN1_PRESS_KEYPAD_1		0x4f
# define SCAN1_PRESS_KEYPAD_2		0x50
# define SCAN1_PRESS_KEYPAD_3		0x51
# define SCAN1_PRESS_KEYPAD_0		0x52
# define SCAN1_PRESS_KEYPAD_DOT		0x53
# define SCAN1_PRESS_F11			0x57
# define SCAN1_PRESS_F12			0x58

# define SCAN1_PRESS_PREVIOUS_TRACK	0x10
# define SCAN1_PRESS_NEXT_TRACK		0x19
# define SCAN1_PRESS_KEYPAD_ENTER	0x1c
# define SCAN1_PRESS_RIGHT_CONTROL	0x1d
# define SCAN1_PRESS_MUTE			0x20
# define SCAN1_PRESS_CALCULATOR		0x21
# define SCAN1_PRESS_PLAY			0x22
# define SCAN1_PRESS_STOP			0x24
# define SCAN1_PRESS_VOLUME_DOWN	0x2e
# define SCAN1_PRESS_VOLUME_UP		0x30
# define SCAN1_PRESS_WWW_HOME		0x32
# define SCAN1_PRESS_KEYPAD_SLASH	0x35
# define SCAN1_PRESS_RIGHT_ALT		0x38
# define SCAN1_PRESS_HOME			0x47
# define SCAN1_PRESS_CURSOR_UP		0x48
# define SCAN1_PRESS_PAGE_UP		0x49
# define SCAN1_PRESS_CURSOR_LEFT	0x4b
# define SCAN1_PRESS_CURSOR_RIGHT	0x4d
# define SCAN1_PRESS_END			0x4f
# define SCAN1_PRESS_CURSOR_DOWN	0x50
# define SCAN1_PRESS_PAGE_DOWN		0x51
# define SCAN1_PRESS_INSERT			0x52
# define SCAN1_PRESS_DELETE			0x53
# define SCAN1_PRESS_LEFT_GUI		0x5b
# define SCAN1_PRESS_RIGHT_GUI		0x5c
# define SCAN1_PRESS_APPS			0x5d
# define SCAN1_PRESS_POWER			0x5e
# define SCAN1_PRESS_SLEEP			0x5f
# define SCAN1_PRESS_WAKE			0x63
# define SCAN1_PRESS_WWW_SEARCH		0x65
# define SCAN1_PRESS_WWW_FAVORITES	0x66
# define SCAN1_PRESS_WWW_REFRESH	0x67
# define SCAN1_PRESS_WWW_STOP		0x68
# define SCAN1_PRESS_WWW_FORWARD	0x69
# define SCAN1_PRESS_WWW_BACK		0x6a
# define SCAN1_PRESS_MY_COMPUTER	0x6b
# define SCAN1_PRESS_EMAIL			0x6c
# define SCAN1_PRESS_MEDIA_SELECT	0x6d

// TODO Pause and print screen

# define SCAN1_RELEASE_ESC				0x81
# define SCAN1_RELEASE_1				0x82
# define SCAN1_RELEASE_2				0x83
# define SCAN1_RELEASE_3				0x84
# define SCAN1_RELEASE_4				0x85
# define SCAN1_RELEASE_5				0x86
# define SCAN1_RELEASE_6				0x87
# define SCAN1_RELEASE_7				0x88
# define SCAN1_RELEASE_8				0x89
# define SCAN1_RELEASE_9				0x8a
# define SCAN1_RELEASE_0				0x8b
# define SCAN1_RELEASE_MINUS			0x8c
# define SCAN1_RELEASE_EQUAL			0x8d
# define SCAN1_RELEASE_BACKSPACE		0x8e
# define SCAN1_RELEASE_TAB				0x8f
# define SCAN1_RELEASE_Q				0x90
# define SCAN1_RELEASE_W				0x91
# define SCAN1_RELEASE_E				0x92
# define SCAN1_RELEASE_R				0x93
# define SCAN1_RELEASE_T				0x94
# define SCAN1_RELEASE_Y				0x95
# define SCAN1_RELEASE_U				0x96
# define SCAN1_RELEASE_I				0x97
# define SCAN1_RELEASE_O				0x98
# define SCAN1_RELEASE_P				0x99
# define SCAN1_RELEASE_LEFT_BRACKET		0x9a
# define SCAN1_RELEASE_RIGHT_BRACKET	0x9b
# define SCAN1_RELEASE_ENTER			0x9c
# define SCAN1_RELEASE_LEFT_CTRL		0x9d
# define SCAN1_RELEASE_A				0x9e
# define SCAN1_RELEASE_S				0x9f
# define SCAN1_RELEASE_D				0xa0
# define SCAN1_RELEASE_F				0xa1
# define SCAN1_RELEASE_G				0xa2
# define SCAN1_RELEASE_H				0xa3
# define SCAN1_RELEASE_J				0xa4
# define SCAN1_RELEASE_K				0xa5
# define SCAN1_RELEASE_L				0xa6
# define SCAN1_RELEASE_SEMICOLON		0xa7
# define SCAN1_RELEASE_SINGLE_QUOTE		0xa8
# define SCAN1_RELEASE_BACKTICK			0xa9
# define SCAN1_RELEASE_LEFT_SHIFT		0xaa
# define SCAN1_RELEASE_BACKSLASH		0xab
# define SCAN1_RELEASE_Z				0xac
# define SCAN1_RELEASE_X				0xad
# define SCAN1_RELEASE_C				0xae
# define SCAN1_RELEASE_V				0xaf
# define SCAN1_RELEASE_B				0xb0
# define SCAN1_RELEASE_N				0xb1
# define SCAN1_RELEASE_M				0xb2
# define SCAN1_RELEASE_COMMA			0xb3
# define SCAN1_RELEASE_DOT				0xb4
# define SCAN1_RELEASE_SLASH			0xb5
# define SCAN1_RELEASE_RIGHT_SHIFT		0xb6
# define SCAN1_RELEASE_KEYPAD_STAR		0xb7
# define SCAN1_RELEASE_LEFT_ALT			0xb8
# define SCAN1_RELEASE_SPACE			0xb9
# define SCAN1_RELEASE_CAPSLOCK			0xba
# define SCAN1_RELEASE_F1				0xbb
# define SCAN1_RELEASE_F2				0xbc
# define SCAN1_RELEASE_F3				0xbd
# define SCAN1_RELEASE_F4				0xbe
# define SCAN1_RELEASE_F5				0xbf
# define SCAN1_RELEASE_F6				0xc0
# define SCAN1_RELEASE_F7				0xc1
# define SCAN1_RELEASE_F8				0xc2
# define SCAN1_RELEASE_F9				0xc3
# define SCAN1_RELEASE_F10				0xc4
# define SCAN1_RELEASE_NUMBERLOCK		0xc5
# define SCAN1_RELEASE_SCROLLLOCK		0xc6
# define SCAN1_RELEASE_KEYPAD_7			0xc7
# define SCAN1_RELEASE_KEYPAD_8			0xc8
# define SCAN1_RELEASE_KEYPAD_9			0xc9
# define SCAN1_RELEASE_KEYPAD_MINUS		0xca
# define SCAN1_RELEASE_KEYPAD_4			0xcb
# define SCAN1_RELEASE_KEYPAD_5			0xcc
# define SCAN1_RELEASE_KEYPAD_6			0xcd
# define SCAN1_RELEASE_KEYPAD_PLUS		0xce
# define SCAN1_RELEASE_KEYPAD_1			0xcf
# define SCAN1_RELEASE_KEYPAD_2			0xd0
# define SCAN1_RELEASE_KEYPAD_3			0xd1
# define SCAN1_RELEASE_KEYPAD_0			0xd2
# define SCAN1_RELEASE_KEYPAD_DOT		0xd3
# define SCAN1_RELEASE_F11				0xd7
# define SCAN1_RELEASE_F12				0xd8

# define SCAN1_RELEASE_PREVIOUS_TRACK	0x90
# define SCAN1_RELEASE_NEXT_TRACK		0x99
# define SCAN1_RELEASE_KEYPAD_ENTER		0x9c
# define SCAN1_RELEASE_RIGHT_CONTROL	0x9d
# define SCAN1_RELEASE_MUTE				0xa0
# define SCAN1_RELEASE_CALCULATOR		0xa1
# define SCAN1_RELEASE_PLAY				0xa2
# define SCAN1_RELEASE_STOP				0xa4
# define SCAN1_RELEASE_VOLUME_DOWN		0xae
# define SCAN1_RELEASE_VOLUME_UP		0xb0
# define SCAN1_RELEASE_WWW_HOME			0xb2
# define SCAN1_RELEASE_KEYPAD_SLASH		0xb5
# define SCAN1_RELEASE_RIGHT_ALT		0xb8
# define SCAN1_RELEASE_HOME				0xc7
# define SCAN1_RELEASE_CURSOR_UP		0xc8
# define SCAN1_RELEASE_PAGE_UP			0xc9
# define SCAN1_RELEASE_CURSOR_LEFT		0xcb
# define SCAN1_RELEASE_CURSOR_RIGHT		0xcd
# define SCAN1_RELEASE_END				0xcf
# define SCAN1_RELEASE_CURSOR_DOWN		0xd0
# define SCAN1_RELEASE_PAGE_DOWN		0xd1
# define SCAN1_RELEASE_INSERT			0xd2
# define SCAN1_RELEASE_DELETE			0xd3
# define SCAN1_RELEASE_LEFT_GUI			0xdb
# define SCAN1_RELEASE_RIGHT_GUI		0xdc
# define SCAN1_RELEASE_APPS				0xdd
# define SCAN1_RELEASE_POWER			0xde
# define SCAN1_RELEASE_SLEEP			0xdf
# define SCAN1_RELEASE_WAKE				0xe3
# define SCAN1_RELEASE_WWW_SEARCH		0xe5
# define SCAN1_RELEASE_WWW_FAVORITES	0xe6
# define SCAN1_RELEASE_WWW_REFRESH		0xe7
# define SCAN1_RELEASE_WWW_STOP			0xe8
# define SCAN1_RELEASE_WWW_FORWARD		0xe9
# define SCAN1_RELEASE_WWW_BACK			0xea
# define SCAN1_RELEASE_MY_COMPUTER		0xeb
# define SCAN1_RELEASE_EMAIL			0xec
# define SCAN1_RELEASE_MEDIA_SELECT		0xed

// TODO Pause and print screen

# define KEY_ESC			0x00
# define KEY_1				0x01
# define KEY_2				0x02
# define KEY_3				0x03
# define KEY_4				0x04
# define KEY_5				0x05
# define KEY_6				0x06
# define KEY_7				0x07
# define KEY_8				0x08
# define KEY_9				0x09
# define KEY_0				0x0a
# define KEY_MINUS			0x0b
# define KEY_EQUAL			0x0c
# define KEY_BACKSPACE		0x0d
# define KEY_TAB			0x0e
# define KEY_Q				0x0f
# define KEY_W				0x10
# define KEY_E				0x11
# define KEY_R				0x12
# define KEY_T				0x13
# define KEY_Y				0x14
# define KEY_U				0x15
# define KEY_I				0x16
# define KEY_O				0x17
# define KEY_P				0x18
# define KEY_LEFT_BRACKET	0x19
# define KEY_RIGHT_BRACKET	0x1a
# define KEY_ENTER			0x1b
# define KEY_LEFT_CTRL		0x1c
# define KEY_A				0x1d
# define KEY_S				0x1e
# define KEY_D				0x1f
# define KEY_F				0x20
# define KEY_G				0x21
# define KEY_H				0x22
# define KEY_J				0x23
# define KEY_K				0x24
# define KEY_L				0x25
# define KEY_SEMICOLON		0x26
# define KEY_SINGLE_QUOTE	0x27
# define KEY_BACKTICK		0x28
# define KEY_LEFT_SHIFT		0x29
# define KEY_BACKSLASH		0x2a
# define KEY_Z				0x2b
# define KEY_X				0x2c
# define KEY_C				0x2d
# define KEY_V				0x2e
# define KEY_B				0x2f
# define KEY_N				0x30
# define KEY_M				0x31
# define KEY_COMMA			0x32
# define KEY_DOT			0x33
# define KEY_SLASH			0x34
# define KEY_RIGHT_SHIFT	0x35
# define KEY_KEYPAD_STAR	0x36
# define KEY_LEFT_ALT		0x37
# define KEY_SPACE			0x38
# define KEY_CAPSLOCK		0x39
# define KEY_F1				0x3a
# define KEY_F2				0x3b
# define KEY_F3				0x3c
# define KEY_F4				0x3d
# define KEY_F5				0x3e
# define KEY_F6				0x3f
# define KEY_F7				0x40
# define KEY_F8				0x41
# define KEY_F9				0x42
# define KEY_F10			0x43
# define KEY_NUMBERLOCK		0x44
# define KEY_SCROLLLOCK		0x45
# define KEY_KEYPAD_7		0x46
# define KEY_KEYPAD_8		0x47
# define KEY_KEYPAD_9		0x48
# define KEY_KEYPAD_MINUS	0x49
# define KEY_KEYPAD_4		0x4a
# define KEY_KEYPAD_5		0x4b
# define KEY_KEYPAD_6		0x4c
# define KEY_KEYPAD_PLUS	0x4d
# define KEY_KEYPAD_1		0x4e
# define KEY_KEYPAD_2		0x4f
# define KEY_KEYPAD_3		0x50
# define KEY_KEYPAD_0		0x51
# define KEY_KEYPAD_DOT		0x52
# define KEY_F11			0x56
# define KEY_F12			0x57

# define KEY_PREVIOUS_TRACK	0x60
# define KEY_NEXT_TRACK		0x69
# define KEY_KEYPAD_ENTER	0x6c
# define KEY_RIGHT_CTRL		0x6d
# define KEY_MUTE			0x70
# define KEY_CALCULATOR		0x71
# define KEY_PLAY			0x72
# define KEY_STOP			0x74
# define KEY_VOLUME_DOWN	0x7e
# define KEY_VOLUME_UP		0x80
# define KEY_WWW_HOME		0x82
# define KEY_KEYPAD_SLASH	0x85
# define KEY_RIGHT_ALT		0x88
# define KEY_HOME			0x97
# define KEY_CURSOR_UP		0x98
# define KEY_PAGE_UP		0x99
# define KEY_CURSOR_LEFT	0x9b
# define KEY_CURSOR_RIGHT	0x9d
# define KEY_END			0x9f
# define KEY_CURSOR_DOWN	0xa0
# define KEY_PAGE_DOWN		0xa1
# define KEY_INSERT			0xa2
# define KEY_DELETE			0xa3
# define KEY_LEFT_GUI		0xab
# define KEY_RIGHT_GUI		0xac
# define KEY_APPS			0xad
# define KEY_POWER			0xae
# define KEY_SLEEP			0xaf
# define KEY_WAKE			0xb3
# define KEY_WWW_SEARCH		0xb5
# define KEY_WWW_FAVORITES	0xb6
# define KEY_WWW_REFRESH	0xb7
# define KEY_WWW_STOP		0xb8
# define KEY_WWW_FORWARD	0xb9
# define KEY_WWW_BACK		0xba
# define KEY_MY_COMPUTER	0xbb
# define KEY_EMAIL			0xbc
# define KEY_MEDIA_SELECT	0xbd

// TODO Pause and print screen

# define KEY_STATE_PRESSED	1
# define KEY_STATE_RELEASED	0

typedef uint8_t key_code_t;
typedef uint8_t key_state_t;

void keyboard_init(void);
key_state_t keyboard_get_state(const key_code_t key);
bool keyboard_is_ctrl_enabled(void);
bool keyboard_is_shift_enabled(void);
bool keyboard_is_capslock_enabled(void);
char keyboard_get_char(const key_code_t code, const bool shift);

void keyboard_set_input_hook(void (*hook)(const key_code_t));
void keyboard_set_ctrl_hook(void (*hook)(const key_code_t));
void keyboard_set_erase_hook(void (*hook)(void));

#endif
