#!/bin/sh

# This script builds kernel modules.

KERN_SRC=$(realpath $(dirname $0)/..)
if [ -z "$ARCH" ]; then
	ARCH="x86"
fi
CARGOFLAGS="--target $KERN_SRC/kernel/arch/$ARCH/$ARCH.json $CARGOFLAGS"

if [ ! -z "$PROFILE" ] && [ "$PROFILE" != "debug" ]; then
	CARGOFLAGS="$CARGOFLAGS --profile $PROFILE"
else
  PROFILE="debug"
fi
export RUSTFLAGS="--extern kernel=$KERN_SRC/kernel/target/$ARCH/$PROFILE/libkernel.so -L $KERN_SRC/kernel/target/$ARCH/$PROFILE/deps -L $KERN_SRC/kernel/target/$PROFILE/deps $RUSTFLAGS"
echo $RUSTFLAGS

cargo build $CARGOFLAGS $@
