#!/bin/sh

# This script is compiles kernel modules.

KERN_SRC=$(realpath $(dirname $0)/..)
if [ "$(pwd)" = "$KERN_SRC" ]; then
	>&2 echo "This script is to be used for kernel modules. Not the kernel itself"
	exit 1
fi

if [ -z "$ARCH" ]; then
	ARCH="x86"
fi
CARGOFLAGS="--target $KERN_SRC/arch/$ARCH/$ARCH.json"

if [ -z "$PROFILE" ]; then
	PROFILE="debug"
fi
export RUSTFLAGS="--extern kernel=$KERN_SRC/target/$ARCH/$PROFILE/libkernel.so -L $KERN_SRC/target/$ARCH/$PROFILE/deps -L $KERN_SRC/target/$PROFILE/deps"

cargo build $CARGOFLAGS $@
