name: Book
on:
  push:
    branches: ["master"]
    paths: ["doc/**"]
  pull_request:
    paths: ["doc/**"]

jobs:
  build:
    name: Build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Cache mdbook binary
        id: cache-mdbook
        uses: actions/cache@v5
        with:
          path: ~/.cargo/bin/mdbook
          key: mdbook-0.5.2-${{ runner.os }}
      - name: Cache mdbook-mermaid binary
        id: cache-mdbook-mermaid
        uses: actions/cache@v5
        with:
          path: ~/.cargo/bin/mdbook-mermaid
          key: mdbook-mermaid-0.17.0-${{ runner.os }}
      - name: Install mdbook
        if: steps.cache-mdbook.outputs.cache-hit != 'true'
        run: cargo +stable install mdbook@0.5.2
      - name: Install mdbook-mermaid
        if: steps.cache-mdbook-mermaid.outputs.cache-hit != 'true'
        run: cargo +stable install mdbook-mermaid@0.17.0

      - name: Prepare
        run: mdbook-mermaid install doc/
      - name: Build book
        run: mdbook build doc/

      - name: Upload book artifact
        uses: actions/upload-artifact@v7
        with:
          name: book
          path: doc/book

  publish:
    name: Publish
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Download book artifact
        uses: actions/download-artifact@v8
        with:
          name: book
      - name: Install rclone
        uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
        with:
          packages: rclone
          version: 1.0
      - name: Sync book to S3
        env:
          RCLONE_CONFIG_CELLAR_TYPE: s3
          RCLONE_CONFIG_CELLAR_PROVIDER: ${{ vars.S3_PROVIDER }}
          RCLONE_CONFIG_CELLAR_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          RCLONE_CONFIG_CELLAR_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_CELLAR_ENDPOINT: ${{ vars.S3_ENDPOINT_URL }}
        run: rclone sync . cellar:${{ vars.S3_BUCKET }} --delete-during
