name: Check
on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  build-binutils:
    name: Build binutils
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - &binutils-cache
        name: Restore binutils cache
        id: cache-binutils
        uses: actions/cache@v5
        with:
          path: built-binutils
          key: binutils-2.46.0
      - name: Build binutils
        if: steps.cache-binutils.outputs.cache-hit != 'true'
        run: |
          curl -o binutils.tar.xz https://ftp.gnu.org/gnu/binutils/binutils-2.46.0.tar.xz
          tar xf binutils.tar.xz
          rm binutils.tar.xz
          for target in {i686-elf,x86_64-elf}; do
            binutils-*/configure \
              --prefix=/usr \
              --target="$target" \
              --disable-werror \
              --disable-doc \
              --disable-nls \
              --enable-64-bit-bfd
            make -j$(nproc)
            make DESTDIR="$(pwd)/built-binutils" install
            make distclean
          done

  lint:
    name: Lint & Check Format (${{ matrix.dir }})
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: ["macros", "utils", "kernel", "inttest"]
    steps:
      - uses: actions/checkout@v6
      - &rust-toolchain-cache
        name: Cache Rust toolchain
        uses: actions/cache@v5
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
          key: rust-toolchain-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}
      - &rust-registry-cache
        name: Restore Rust registry cache
        uses: actions/cache/restore@v5
        with: &rust-registry-cache-params
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: rust-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: rust-registry-${{ runner.os }}-
      - name: Clippy
        working-directory: ${{ matrix.dir }}
        run: cargo clippy --all-features --all-targets -- -D warnings
      - name: Check Format
        working-directory: ${{ matrix.dir }}
        run: cargo fmt --check

  documentation:
    name: Build Documentation (${{ matrix.arch }})
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86", "x86_64"]
    steps:
      - uses: actions/checkout@v6
      - *rust-toolchain-cache
      - *rust-registry-cache
      - name: Build references
        working-directory: kernel
        run: cargo doc --target arch/${{ matrix.arch }}/${{ matrix.arch }}.json

  miri:
    name: Miri
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - *rust-toolchain-cache
      - *rust-registry-cache
      - name: Utils
        working-directory: utils
        env:
          MIRIFLAGS: -Zmiri-disable-stacked-borrows
        run: cargo miri test
        timeout-minutes: 10

  build:
    name: Build (${{ matrix.arch }}, ${{ matrix.profile.dir }})
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: [lint, build-binutils]
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86", "x86_64"]
        profile:
          - name: "dev"
            dir: "debug"
          - name: "release"
            dir: "release"
    steps:
      - uses: actions/checkout@v6
      - *rust-toolchain-cache
      - name: Cache Rust registry
        uses: actions/cache@v5
        with: *rust-registry-cache-params
      - *binutils-cache
      - &binutils-path
        name: Add binutils to PATH
        run: echo "$(pwd)/built-binutils/usr/bin" >> $GITHUB_PATH
      - &apt-cache
        name: Retrieve APT dependencies
        uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
        with:
          packages: bash build-essential clang curl grub-pc-bin libssl-dev lld mtools perl pkg-config qemu-system texinfo xorriso
          version: 1.0
      - name: Build
        working-directory: kernel
        run: cargo build --target arch/${{ matrix.arch }}/${{ matrix.arch }}.json --profile ${{ matrix.profile.name }}
      - name: Check Multiboot2
        working-directory: kernel
        run: grub-file --is-x86-multiboot2 target/${{ matrix.arch }}/${{ matrix.profile.dir }}/maestro
      - name: Remove binutils (should not be in workspace artifact)
        run: rm -rf built-binutils
      - name: Upload ${{ matrix.arch }}-${{ matrix.profile.dir }} workspace
        uses: actions/upload-artifact@v7
        with:
          name: workspace-${{ matrix.arch }}-${{ matrix.profile.dir }}
          path: .
          include-hidden-files: true

  module:
    name: Build Module ${{ matrix.mod }} (${{ matrix.arch }}, ${{ matrix.profile }})
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        mod: ["e1000", "ps2"]
        arch: ["x86", "x86_64"]
        profile: ["debug", "release"]
    steps:
      - name: Restore ${{ matrix.arch }}-${{ matrix.profile }} workspace
        uses: actions/download-artifact@v8
        with:
          name: workspace-${{ matrix.arch }}-${{ matrix.profile }}
      - name: Restore permissions
        run: chmod +x mod/build
      - *rust-toolchain-cache
      - *rust-registry-cache
      - *binutils-cache
      - *binutils-path
      - name: Clippy
        working-directory: mod/${{ matrix.mod }}
        env:
          ARCH: ${{ matrix.arch }}
          CMD: clippy
          PROFILE: ${{ matrix.profile }}
        run: ../build -- -D warnings
      - name: Format
        working-directory: mod/${{ matrix.mod }}
        run: cargo fmt --check
      - name: Build
        working-directory: mod/${{ matrix.mod }}
        env:
          ARCH: ${{ matrix.arch }}
          PROFILE: ${{ matrix.profile }}
        run: ../build

  selftest:
    name: Self Test (${{ matrix.arch }})
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86", "x86_64"]
    steps:
      - uses: actions/checkout@v6
      - *rust-toolchain-cache
      - *rust-registry-cache
      - *apt-cache
      - *binutils-cache
      - *binutils-path
      - name: Run utils tests
        working-directory: utils
        run: cargo test
        timeout-minutes: 10
      - name: Run kernel tests
        working-directory: kernel
        env:
          CARGOFLAGS: --target arch/${{ matrix.arch }}/${{ matrix.arch }}.json
        run: ci/test.sh self
        timeout-minutes: 10

  build_inttest:
    name: Build Integration Tests Disks (${{ matrix.arch.kernel }})
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        arch:
          - kernel: "x86"
            user: "i686-unknown-linux-musl"
          - kernel: "x86_64"
            user: "x86_64-unknown-linux-musl"
            user_compat: "i686-unknown-linux-musl"
    steps:
      - &restore-dbg-workspace
        name: Restore ${{ matrix.arch.kernel }}-debug workspace
        uses: actions/download-artifact@v8
        with:
          name: workspace-${{ matrix.arch.kernel }}-debug
      - name: Restore permissions
        run: chmod +x mod/build inttest/build.sh
      - *rust-toolchain-cache
      - *rust-registry-cache
      - *binutils-cache
      - *binutils-path
      - name: Build tests
        working-directory: inttest
        env:
          ARCH: ${{ matrix.arch.kernel }}
          TARGET: ${{ matrix.arch.user }}
        run: |
          ./build.sh
          mv disk disk-${{ matrix.arch.kernel }}
      - name: Build tests (compat)
        if: ${{ matrix.arch.user_compat }}
        working-directory: inttest
        env:
          ARCH: ${{ matrix.arch.kernel }}
          TARGET: ${{ matrix.arch.user_compat }}
        run: |
          ./build.sh
          mv disk disk-${{ matrix.arch.kernel }}-compat
      - name: Upload disk images
        uses: actions/upload-artifact@v7
        with:
          name: inttest-disks-${{ matrix.arch.kernel }}
          path: inttest/disk-${{ matrix.arch.kernel }}*

  inttest:
    name: Run Integration Tests (${{ matrix.arch.kernel }}, ${{ matrix.cores }} CPU(s), ${{ matrix.disktype }})
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: build_inttest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - kernel: "x86"
            user: "i686-unknown-linux-musl"
          - kernel: "x86_64"
            user: "x86_64-unknown-linux-musl"
            user_compat: "i686-unknown-linux-musl"
        cores: ["1", "2"]
        disktype: ["ide", "nvme"]
    steps:
      - uses: actions/checkout@v6
      - name: Restore disk images
        uses: actions/download-artifact@v8
        with:
          name: inttest-disks-${{ matrix.arch.kernel }}
      - *rust-toolchain-cache
      - *rust-registry-cache
      - *apt-cache
      - *binutils-cache
      - *binutils-path
      - name: Run
        working-directory: kernel
        env:
          CARGOFLAGS: --target arch/${{ matrix.arch.kernel }}/${{ matrix.arch.kernel }}.json
          QEMUFLAGS: "-smp ${{ matrix.cores }}"
          DISKTYPE: ${{ matrix.disktype }}
        run: |
          mv ../disk-${{ matrix.arch.kernel }} qemu_disk
          ci/test.sh int
        timeout-minutes: 10
      - name: Run (compat)
        if: ${{ matrix.arch.user_compat }}
        working-directory: kernel
        env:
          CARGOFLAGS: --target arch/${{ matrix.arch.kernel }}/${{ matrix.arch.kernel }}.json
          QEMUFLAGS: "-smp ${{ matrix.cores }}"
          DISKTYPE: ${{ matrix.disktype }}
        run: |
          mv ../disk-${{ matrix.arch.kernel }}-compat qemu_disk
          ci/test.sh int
        timeout-minutes: 10
